global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-notifications'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - api_url: 'https://api.telegram.org'
    bot_token: '<токен вашего бота>'
    chat_id: <ID чата, в который бот будет присылать уведомления>
    message: |
      {{ range .Alerts }}
      <b>Alert:</b> {{ .Annotations.summary }}
      <b>Instance:</b> {{ .Labels.instance }}
      <b>Severity:</b> {{ .Labels.severity }}
      <b>Details:</b>
      {{ .Annotations.description }}
      {{ end }}